language: python

python:
  - "3.4"

before_install:
  - "sudo apt-get install -y python3-lxml"

install:
  - "pip install -r requirements.txt"
  - "npm install -g typescript"
  - "git clone --depth 1 git@github.com:borisyankov/DefinitelyTyped.git static/DefinitelyTyped"

before_script:
  - "sh deploy/before_script.sh"

script:
  - "python3 generator.py"

after_success:
  - "sh deploy/after_success.sh"

addons:
  ssh_known_hosts: github.com

branches:
  except:
    - gh-pages
