language: python

python:
  - "3.4"

before_install:
  - apt-get install -y python3-lxml

install:
  - "pip install -r requirements.txt"
  - "npm install -g typescript"

before_script:
  - "sh deploy/before_script.sh"

script:
  - "python3 generator.py"

deploy:
  - "sh deploy/deploy.sh"

addons:
  ssh_known_hosts: github.com

branches:
  except:
    - gh-pages
