language: python

python:
  - "3.4"

install:
  - "pip install -r requirements.txt"
  - "npm install -g typescript"

script:
  - "python3 generator.py"

addons:
  ssh_known_hosts: github.com

branches:
  except:
    - gh-pages
